# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articulos_Cientificos', '0001_initial'),
        ('palabraClave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePonencia', models.CharField(max_length=150)),
                ('lugarPonencia', models.CharField(max_length=150)),
                ('tituloPonencia', models.CharField(max_length=70)),
                ('fechaPonencia', models.DateField()),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('nivelAutoria', models.CharField(blank=True, max_length=100, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('certificado', models.CharField(blank=True, max_length=100, null=True)),
                ('urlPonencia', models.URLField(blank=True, null=True)),
                ('financiamiento', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, null=True)),
                ('informe', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('articuloCientifico', models.ManyToManyField(to='Articulos_Cientificos.articulos_cientificos')),
                ('palabrasClave', models.ManyToManyField(to='palabraClave.palabraClave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
