# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.7 on 2018-05-10 21:34
=======
# Generated by Django 1.11.7 on 2018-05-13 20:20
>>>>>>> 190d19e7efff91de1d19fc35b9343adb30edf859
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_profecionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Profecion', models.CharField(max_length=255)),
                ('Grado_Cientifico', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('ver_datosprofesionales', 'ver datosprofesionales'),),
            },
        ),
    ]
