# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fechaInicial', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('gradoAutoria', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('ver_investigaciones', 'ver investigaciones'),),
            },
        ),
    ]
