# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.7 on 2018-05-10 21:34
=======
# Generated by Django 1.11.7 on 2018-05-13 20:20
>>>>>>> 190d19e7efff91de1d19fc35b9343adb30edf859
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='investigador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(blank=True, max_length=10)),
                ('Direccion', models.CharField(blank=True, max_length=500)),
                ('Coordenadas', models.CharField(blank=True, max_length=450)),
                ('Telefono', models.CharField(blank=True, max_length=10)),
                ('Genero', models.CharField(blank=True, max_length=100)),
                ('Ciudadania', models.CharField(blank=True, max_length=100)),
                ('carrera', models.ManyToManyField(to='carrera.carrera')),
            ],
        ),
    ]
