# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palabraClave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Linea_Investigacion', '0001_initial'),
        ('Revista', '0001_initial'),
        ('baseDatos', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos_cientificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('iSSN', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=300)),
                ('doi', models.URLField(max_length=300)),
                ('fechaPublicacion', models.DateField()),
                ('ciudad', models.CharField(max_length=150)),
                ('volumen', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=150)),
                ('resumen', models.TextField(max_length=150)),
                ('documento', models.FileField(blank=True, null=True, upload_to='')),
                ('tipoArticulo', models.CharField(max_length=150)),
                ('gradoAutoria', models.CharField(max_length=150)),
                ('aprobado', models.CharField(max_length=150)),
                ('SubLinea', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
                ('baseDatos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseDatos.baseDatos')),
                ('lineaInves', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='Linea_Investigacion.linea_investigacion')),
                ('palabraClave', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='palabraClave.palabraClave')),
                ('revista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Revista.revista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_articulo', 'ver articulo'),),
            },
        ),
    ]
