# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.7 on 2018-05-10 21:34
=======
# Generated by Django 1.11.7 on 2018-05-13 20:20
>>>>>>> 190d19e7efff91de1d19fc35b9343adb30edf859
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Linea_Investigacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palabraClave', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
=======
        ('Sub_Lin_Investigacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Linea_Investigacion', '0001_initial'),
        ('palabraClave', '0001_initial'),
>>>>>>> 190d19e7efff91de1d19fc35b9343adb30edf859
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('financiamiento', models.CharField(max_length=2)),
                ('montoFinanciado', models.CharField(max_length=200)),
                ('montorecibido', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='proyecto/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('integrantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lineaInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Linea_Investigacion.linea_investigacion')),
                ('palabrasClaves', models.ManyToManyField(to='palabraClave.palabraClave')),
                ('subLinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
            ],
            options={
                'permissions': (('ver_Proyectos', 'ver Proyectos'),),
            },
        ),
    ]
