# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseDatos', '0001_initial'),
        ('palabraClave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(error_messages={'required': 'Por favor, ingrese un titulo'}, max_length=200)),
                ('ISBN', models.CharField(blank=True, max_length=100, null=True)),
                ('Anio', models.CharField(blank=True, max_length=4, null=True)),
                ('Editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('Resumen', models.TextField(null=True)),
                ('Documento', models.FileField(blank=True, null=True, upload_to='libro/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Url', models.URLField(blank=True, null=True)),
                ('Doi', models.URLField(blank=True, max_length=100, null=True)),
                ('UbicacionFisica', models.CharField(blank=True, max_length=200, null=True)),
                ('capitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('gradoAutoria', models.CharField(blank=True, max_length=50, null=True)),
                ('BaseDatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseDatos.baseDatos')),
                ('PalabrasClave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palabraClave.palabraClave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_libro', 'ver libro'),),
            },
        ),
    ]
