# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ambito_Investigativo', '0001_initial'),
        ('Investigador', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='palabra_clave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Termino', models.CharField(max_length=100)),
                ('Termino', models.CharField(max_length=20)),
                ('ambito_investigativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ambito_Investigativo.ambito_investigativo')),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.investigador')),
                ('sub_lin_investigacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
            ],
        ),
    ]
